export enum Chain {
  Ethereum = 'ethereum',
  Scroll = 'scroll',
  Mantle = 'mantle',
  Linea = 'linea',
  Base = 'base',
  Arbitrum = 'arbitrum',
  zkSync = 'zkSync',
  BNB = 'bnb',
  Polygon = 'polygon',
  Klaytn = 'klaytn',
  zkEVM = 'zkEVM',
  Avalanche = 'avax',
  Optimism = 'optimism',
  Cronos = 'cronos',
  Fantom = 'fantom',
  Astar = 'astar',
  KCC = 'kcc',
  Moonriver = 'moonriver',
  ThunderCore = 'thunderCore',
  Numbers = 'numbers',
}

export const YBridgeContractAddress: Record<Chain, string> = {
  [Chain.Ethereum]: '0x4315f344a905dC21a08189A117eFd6E1fcA37D57',
  [Chain.Scroll]: "",
  [Chain.Mantle]: "",
  [Chain.Linea]: "",
  [Chain.Base]: "",
  [Chain.Arbitrum]: "",
  [Chain.zkSync]: "",
  [Chain.BNB]: "",
  [Chain.Polygon]: "",
  [Chain.Klaytn]: "",
  [Chain.zkEVM]: "",
  [Chain.Avalanche]: "",
  [Chain.Optimism]: "",
  [Chain.Cronos]: "",
  [Chain.Fantom]: "",
  [Chain.Astar]: "",
  [Chain.KCC]: "",
  [Chain.Moonriver]: "",
  [Chain.ThunderCore]: "",
  [Chain.Numbers]: ""
}