import { chainMappings } from "../helpers/tokenMappings";

// Provider aliases are intentionally separate from token/IBC mappings. Kava and
// Sei have both EVM networks and Cosmos zone IDs, so using the shared mapping for
// normal adapters sends EVM block lookups to kava_2222-10 and pacific-1.
export const providerChainAliases: Record<string, string> = {
  avalanche: "avax",
  bittensor: "bittensor_evm",
  gnosis: "xdai",
  "zksync era": "era",
  zksync: "era",
  zksync_era: "era",
  "polygon zkevm": "polygon_zkevm",
  "robinhood chain": "robinhood",
  zkpolygon: "polygon_zkevm",
  polygonzkevm: "polygon_zkevm",
  "arbitrum nova": "arbitrum_nova",
  rootstock: "rsk",
  bsquared: "b2-mainnet",
  "x layer": "xlayer",
  x_layer: "xlayer",
  bouncebit: "bouncebit-mainnet",
  bb1: "bouncebit",
  opbnb: "op_bnb",
  "opbnb mainnet": "op_bnb",
  bitlayer: "btr",
  "aleph zero evm": "aleph_zero",
  ape: "apechain",
  "ape chain": "apechain",
  apex: "pop_apex",
  "astar zkevm": "astrzk",
  astar_zkevm: "astrzk",
  bera: "berachain",
  bnb: "bsc",
  "boba bnb": "boba_bnb",
  boss: "pop_boss",
  chiliz: "chz",
  coredao: "core",
  "cronos zkevm": "cronos_zkevm",
  cronosevm: "cronos",
  cyber: "cyeth",
  dfk_chain: "dfk",
  etherlink: "etlk",
  "function x": "functionx",
  gravity_bridge: "gravity",
  hsk: "hsk",
  horizen: "eon",
  "immutable zkevm": "imx",
  "injective evm": "injective",
  iota: "iotaevm",
  islander: "vana",
  kaia: "klaytn",
  kalychain: "kaly",
  lightlink: "lightlink_phoenix",
  mantra: "mantrachain",
  "map relay chain": "map",
  mc: "merlin",
  "mind network": "mind",
  mp1: "manta",
  "okt chain": "okexchain",
  okx: "okexchain",
  "okxchain mainnet": "okexchain",
  "pgn (public goods network)": "pgn",
  plume: "plume_mainnet",
  "plume mainnet": "plume_mainnet",
  plumephoenix: "plume_mainnet",
  "proof of play": "pop",
  "proof of play apex": "pop_apex",
  "proof of play boss": "pop_boss",
  pulsechain: "pulse",
  "rari chain": "rari",
  rari_chain: "rari",
  rarible: "rari",
  "re.al": "real",
  shimmer: "shimmer_evm",
  shimmerevm: "shimmer_evm",
  superposition: "spn",
  swell: "swellchain",
  tomo: "tomochain",
  viction: "tomochain",
  vinuchain: "vinu",
  wanchain: "wan",
  "world chain": "wc",
  worldchain: "wc",
  xchain: "idex",
  "zero network": "zero_network",
  zetachain: "zeta",
  kava: "kava",
  sei: "sei",
};

export const normalizeAdapterChainName = (chain: string) => chain.trim().toLowerCase();

export const resolveProviderChain = (chain: string, bridgeDbName?: string): string => {
  const normalized = normalizeAdapterChainName(chain);
  if (bridgeDbName === "ibc") return chainMappings[normalized] ?? normalized;
  return providerChainAliases[normalized] ?? normalized;
};
